/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "A new age awaits": "一个新时代正在等待我们",
    "ACTIVATE": "激活",
    "BUY": "购买",
    "BUY!": "购买！",
    "Buy!": "购买！",
    "Buys Extractor upgrades if you can afford them, without expending cells": "购买提取器升级，如果你负担得起，不消耗细胞",
    "DATA": "数据",
    "Core": "核心",
    "EQUIP": "装备",
    "ENERGY": "能量",
    "Data Unlocked": "数据已解锁",
    "Data Automation": "数据自动化",
    "Export Save": "导出存档",
    "EXTRACTOR": "提取器",
    "Hardware": "硬件",
    "HEAVY": "重",
    "Heavy": "重",
    "Import Save": "导入存档",
    "Light": "轻",
    "LIGHT": "轻",
    "LOADOUT": "预设",
    "Manual Save": "手动保存",
    "Medium": "中",
    "MEDIUM": "中",
    "New Horizons": "新视野",
    "NOT UNLOCKED": "未解锁",
    "Progress": "进度",
    "PROJECTS": "项目",
    "Select": "选择",
    "RESET SAVE": "重置游戏",
    "REMOVE": "移除",
    "Projects Unlocked": "项目已解锁",
    "Software": "软件",
    "selects the Data Type with the least aquired data Upgrades": "选择所需的数据升级最少的数据类型",
    "SPEED": "速度",
    "FIRST PILLAR": "第一支柱",
    "First Pillar": "第一支柱",
    "The First Pillar": "第一支柱",
    "THE FIRST PILLAR": "第一支柱",
    "The first drill is built, it is weak and lonely but never stops working.": "第一个钻头建好了，它脆弱而孤独，但从未停止工作。",
    "The Pillar is necessary for people to live in the structure, it has all necessities, many\n                    will grow to the sky, separated by a sea of machines.": "柱子是人们生活所必需的结构，它拥有所有的必需品，许多\n将生长到天空，由机器的海洋隔开。",
    "The structure after many iterations is finally finding his true path, people start accepting this\n                    reality.": "结构经过多次迭代终于找到了自己真正的路径，人们开始接受这个现实。",
    "This is the way for the structure to grow.": "这是结构成长的方式。",
    "Two Cells filament give a simple command, a hundred are able to make a decision, a thousand make a\n                    thought, ten thousand make a change.": "两个细胞发出一个简单的指令，一百个细胞能做出一个决定，一千个细胞能做出一个想法，一万个细胞能做出一个改变。",
    "REALLOCATE THIS TIER (reset this energy structures, doesnt give\n                            resources invested back)": "重新分配这个层(重置这个能量结构，不返还投入的资源)",
    "Looking at the stars inspired countless generations to dream bigger, and set sight on something\n                    greater on themself, can the structure dream? will its path be forged in the stars?": "仰望星空激励了无数代人去实现更大的梦想，并把目光投向更伟大的自己，结构能梦想吗?它的路径会在星空中被锻造吗?",
    "In a lonely place, a scientist was working on a machine that could grow forever.\n                    After decades his work was stalling, the machine could not grow without help.\n                    In the vastness of the universe, hundreds of dimensions far from earth an Entity responded.\n                    It gave the Structure life, it was called USER": "在一个偏僻的地方，一位科学家正在研究一种可以永远生长的机器。几十年后，他的工作停滞不前，机器无法在没有帮助的情况下发展。\n在浩瀚的宇宙中，在远离地球的数百个维度中，有一个实体回应了。它给了结构生命，它被称为用户",
    "One must use all his resources to make progress real, tinker, build, think, create!": "一个人必须利用他所有的资源来取得真正的进步，修补、建造、思考、创造!",
    "REFINING": "精炼",
    "save": "保存",
    "stop": "停止",
    "New Projects New Me": "新的项目新的我",
    "load": "加载",
    "LEVEL UP": "升级",
    "Initiate Hardware": "初始化硬件",
    "EXTRACTORS": "提取器",
    "Extractor  Automation": "提取器自动化",
    "Extractor Unlocked": "提取器已解锁",
    "Every City destroyed and rebuilt, every human inhabits the pillars, the gray walls give life, the\n                    humming machines give peace, and we humans will feed the structure, because the structure must grow.": "每一座被摧毁和重建的城市，每一个人都住在柱子上，灰色的墙给了生命，嗡嗡作响的机器给了和平，我们人类将为结构提供养分，因为结构必须成长。",
    "Earth crust starts being tempered.": "地壳开始变软。",
    "DISCLAIMER: the game is currently under development, future updates could radically\n                    change the game, this could lead to the inability to the system to accept previous saves": "免责声明:游戏目前正在开发中，未来的更新可能会彻底改变游戏，这可能导致系统无法接受以前的存档",
    "CURRENT ENDGAME, THANKS FOR PLAYING": "当前游戏结束，感谢您的参与",
    "Components are the heart of the structure, they decide the direction in which progress is made,\n                    never forget them, inventions will become obsolete, but not components.": "组件是结构的核心，它们决定着前进的方向，永远不要忘记它们，发明会过时，但组件不会。",
    "Energy flows in every crevice of the structure, never filling it enough, seeking a way to make this\n                    overflowing energy a stepping stone for your never ending expansion.": "能量在结构的每一个缝隙中流动，永远不会填满它，寻找一种方法，使这无限的能量成为你永无止境的扩张的垫脚石。",
    "ACTIVE COMPONENTS EFFECTS": "有效组件效果",
    "BUILD THE FIRST STRATUM": "建造第一层",
    "CLICK ON DATA TYPE \"LIGHT\" TO START, \"MEDIUM\" AND \"HEAVY\" WILL BE AVAIABLE\n                        WHEN THEIR BAR IS GREEN.\n                        WHEN A BAR IS FILLED IT WILL GENERATE AN UPGRADE OF THE FOLLOWING DATA TYPE.": "点击数据类型\"轻\"开始，\"中\"和\"重\"将可用，当他们的栏是绿色的。当一个数据条被填满时，它将生成以下数据类型的升级。",
    "Energy, life of the structure": "能量，结构的生命",
    "Catch\n                                        Asteroids": "捕捉\n小行星",
    "Catch Space\n                                        Dust": "捕捉太空\n尘埃",
    "do nothing": "什么都不做",
    "EVERY 10 UPGRADES IT BOOSTS THE COMPONENT": "每升级10次，它就会提升组件",
    "EXPLORATION": "探索",
    "COMPONENTS": "组件",
    "Communication": "通信",
    "Extractor Automation": "提取器自动化",
    "Glimpse in a black\n                                        hole": "对黑洞的一瞥",
    "Glimpse in the\n                                        sun": "在太阳下的一瞥",
    "Cells Producer": "细胞生产者",
    "BETTER CPU": "更好的CPU",
    "Rarity": "稀有度",
    "Components": "组件",
    "collects data faster, and unlocks new types of data": "更快地收集数据，并解锁新的数据类型",
    "Ally Synergy": "盟友协同",
    "Asteroid Cells Booster": "小行星细胞助推器",
    "Asteroid Enchancher": "小行星强化器",
    "Asteroid Data Booster": "小行星数据助推器",
    "Booster": "助推器",
    "Data Producer": "数据生产者",
    "Energy Synergy": "能量协同",
    "Multimaker": "多重制造者",
    "Tick Incrementer": "Tick增量器",
    "DATA AUTOMATION": "数据自动化",
    "COMPONENTS AUTOMATION": "组件自动化",
    "DEEP EXPLORATION": "深入探索",
    "EXPAND CPU": "扩展CPU",
    "Energy Layer": "能量层",
    "Extraction is slightly boosted": "提取量略有增加",
    "EXTRACTOR AUTOMATION": "提取器自动化",
    "FIRST EXPLORATION COMPONENTS": "第一个探索组件",
    "Hardware T1 layer is slightly cheaper": "硬件 T1 层稍微便宜一些",
    "FIRST STRATUM": "第一层",
    "Multimakers are slightly stronger": "多重制造者稍微强一些",
    "RARITY AUTOMATION": "稀有度自动化",
    "Rarity Layer": "稀有层",
    "you can extract more data from each type": "您可以从每种类型中提取更多数据",
    "Data Booster": "数据助推器",
    "Cells Booster": "细胞助推器",
    "Tick booster": "Tick助推器",
    "Boosters are stronger": "助推器更强",
    "Components Cost is reduced": "组件成本降低了",
    "Components rankup are slightly stronger": "组件升阶略微增强",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "MULTIPLIES EXTRACTOR BASE X": "乘以提取器基数 x",
    "COMPLETE THE PROJECT: ": "完成项目: ",
    "cells/s": "细胞/秒",
    "adds to the base of cells/s: ": "添加到 细胞/秒 的基数:",
    "Automation: ": "自动化: ",
    "Component: ": "组件: ",
    "Idle time extension: ": "放置时间延长: ",
    "MILESTONE: ": "里程碑: ",
    "Options:": "选项:",
    "[SOFTWARE][producer]": "[软件][生产者]",
    "[SOFTWARE][booster]": "[软件][助推器]",
    "[HARDWARE][booster]": "[硬件][助推器]",
    "[HARDWARE][producer]": "[硬件][生产者]",
    "More cells -> More Cells/s X: ": "更多细胞 -> 更多细胞/秒 X: ",
    "[SOFTWARE]": "[软件]",
    "[HARDWARE]": "[硬件]",
    "data X: ": "数据 X: ",
    "each resource: x": "每种资源: x",
    "tickspeed X: ": "tick速度 X: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)\/([\d\.]+) ([\d\.]+)$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Removes Limit (.+) on Data, data (.+)$/, '移除数据限制 $1，数据 $2'],
    [/^HARDWARE LAYER AT (.+) CELLS$/, '硬件层在 $1 细胞'],
    [/^SOFTWARE LAYER AT (.+) CELLS$/, '软件层在 $1 细胞'],
    [/^EXPLORATION AT (.+) ENERGY$/, '探索在 $1 能量'],
    [/^PROJECTS AT (.+) DATA$/, '项目在 $1 数据'],
    [/^NEXT PROJECTS AT (.+) DATA$/, '下一个项目在 $1 数据'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) Cells$/, '$1e$2 细胞'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) cells$/, '$1 细胞'],
    [/^([\d\.]+)e([\d\.,]+) Data$/, '$1e$2 数据'],
    [/^([\d\.]+)e([\d\.,]+) cells$/, '$1e$2 细胞'],
    [/^asteroids: ([\d\.]+)$/, '小行星: $1'],
    [/^asteroids: ([\d\.]+)e([\d\.,]+)$/, '小行星: $1e$2'],
    [/^energy: ([\d\.]+)e([\d\.,]+)$/, '能量: $1e$2'],
    [/^Data \+ ([\d\.]+)\/s$/, '数据 \+ $1\/秒'],
    [/^cells: ([\d\.]+)$/, '细胞: $1'],
    [/^price: ([\d\.]+) data$/, '价格: $1 数据'],
    [/^price: ([\d\.]+)e([\d\.,]+) data$/, '价格: $1e$2 数据'],
    [/^energy: ([\d\.]+)$/, '能量: $1'],
    [/^data: ([\d\.]+)$/, '数据: $1'],
    [/^data: ([\d\.]+)e([\d\.,]+)$/, '数据: $1e$2'],
    [/^cells: ([\d\.]+)e([\d\.,]+)$/, '细胞: $1e$2'],
    [/^effect: ([\d\.]+) \/ ([\d\.,]+)$/, '效果: $1 \/ $2'],
    [/^([\d\.]+) Cells$/, '$1 细胞'],
    [/^([\d\.]+) Asteroids$/, '$1 小行星'],
    [/^([\d\.]+) cells\/s$/, '$1 细胞\/秒'],
    [/^([\d\.]+)e([\d\.,]+) cells\/s$/, '$1e$2 细胞\/秒'],
    [/^([\d\.]+) Data$/, '$1 数据'],
    [/^([\d\.]+) Energy$/, '$1 能量'],
    [/^([\d\.]+) Energy\/s$/, '$1 能量\/秒'],
    [/^([\d\.]+)\/([\d\.]+) Energy\/s$/, '$1\/$2 能量\/秒'],
    [/^([\d\.]+)\/([\d\.]+) Energy$/, '$1\/$2 能量'],
    [/^([\d\.]+)\/([\d\.]+)\| price: (.+) cells$/, '$1\/$2 能量\| 价格: $3 细胞'],
    [/^([\d\.]+) Data\/s$/, '$1 数据\/秒'],
    [/^([\d\.]+) Asteroids\/s$/, '$1 小行星\/秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) hour$/, '$1 小时'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) TO THE EXTRACTOR BASE$/, '$1 到提取器基数'],
    [/^Adds \+([\d\.,]+) to the base$/, '增加 \+$1 到基数'],
    [/^SOFTWARE PACKAGE ([\d\.,]+)$/, '软件包 $1'],
    [/^HARDWARE PACKAGE ([\d\.,]+)$/, '硬件包 $1'],
    [/^IDLE ([\d\.,]+)$/, '放置 $1'],
    [/^NEW RESOURCES PACKAGE ([\d\.,]+)$/, '新资源包 $1'],
    [/^Will Unlock K([\d\.,]+)$/, '将会解锁 K$1'],
    [/^LOADOUT ([\d\.,]+)$/, '预设 $1'],
    [/^multiplies Base x([\d\.,]+)$/, '乘以基数 x$1'],
    [/^COMMUNICATION PACKAGE ([\d\.,]+)$/, '通信包 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^price: (.+) cells$/, '价格：$1 细胞'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);