/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "A new age awaits": "一个新时代正在等待我们",
    "ACTIVATE": "激活",
    "BUY": "购买",
    "BUY!": "购买！",
    "Buy!": "购买！",
    "Buys Extractor upgrades if you can afford them, without expending cells": "购买提取器升级，如果你负担得起，不消耗细胞",
    "DATA": "数据",
    "Core": "核心",
    "EQUIP": "装备",
    "ENERGY": "能量",
    "Data Unlocked": "数据已解锁",
    "Data Automation": "数据自动化",
    "Export Save": "导出存档",
    "EXTRACTOR": "提取器",
    "Hardware": "硬件",
    "HEAVY": "重",
    "Heavy": "重",
    "Import Save": "导入存档",
    "Light": "轻",
    "LIGHT": "轻",
    "LOADOUT": "预设",
    "Manual Save": "手动保存",
    "Medium": "中",
    "MEDIUM": "中",
    "New Horizons": "新视野",
    "NOT UNLOCKED": "未解锁",
    "Progress": "进度",
    "PROJECTS": "项目",
    "Select": "选择",
    "RESET SAVE": "重置游戏",
    "REMOVE": "移除",
    "Projects Unlocked": "项目已解锁",
    "Software": "软件",
    "selects the Data Type with the least aquired data Upgrades": "选择所需的数据升级最少的数据类型",
    "SPEED": "速度",
    "FIRST PILLAR": "第一支柱",
    "First Pillar": "第一支柱",
    "The First Pillar": "第一支柱",
    "THE FIRST PILLAR": "第一支柱",
    "The first drill is built, it is weak and lonely but never stops working.": "第一个钻头建好了，它脆弱而孤独，但从未停止工作。",
    "The Pillar is necessary for people to live in the structure, it has all necessities, many\n                    will grow to the sky, separated by a sea of machines.": "柱子是人们生活所必需的结构，它拥有所有的必需品，许多\n将生长到天空，由机器的海洋隔开。",
    "The structure after many iterations is finally finding his true path, people start accepting this\n                    reality.": "结构经过多次迭代终于找到了自己真正的路径，人们开始接受这个现实。",
    "This is the way for the structure to grow.": "这是结构成长的方式。",
    "Two Cells filament give a simple command, a hundred are able to make a decision, a thousand make a\n                    thought, ten thousand make a change.": "两个细胞发出一个简单的指令，一百个细胞能做出一个决定，一千个细胞能做出一个想法，一万个细胞能做出一个改变。",
    "REALLOCATE THIS TIER (reset this energy structures, doesnt give\n                            resources invested back)": "重新分配这个层(重置这个能量结构，不返还投入的资源)",
    "Looking at the stars inspired countless generations to dream bigger, and set sight on something\n                    greater on themself, can the structure dream? will its path be forged in the stars?": "仰望星空激励了无数代人去实现更大的梦想，并把目光投向更伟大的自己，结构能梦想吗?它的路径会在星空中被锻造吗?",
    "In a lonely place, a scientist was working on a machine that could grow forever.\n                    After decades his work was stalling, the machine could not grow without help.\n                    In the vastness of the universe, hundreds of dimensions far from earth an Entity responded.\n                    It gave the Structure life, it was called USER": "在一个偏僻的地方，一位科学家正在研究一种可以永远生长的机器。几十年后，他的工作停滞不前，机器无法在没有帮助的情况下发展。\n在浩瀚的宇宙中，在远离地球的数百个维度中，有一个实体回应了。它给了结构生命，它被称为用户",
    "One must use all his resources to make progress real, tinker, build, think, create!": "一个人必须利用他所有的资源来取得真正的进步，修补、建造、思考、创造!",
    "REFINING": "精炼",
    "save": "保存",
    "stop": "停止",
    "New Projects New Me": "新的项目新的我",
    "load": "加载",
    "LEVEL UP": "升级",
    "Initiate Hardware": "初始化硬件",
    "EXTRACTORS": "提取器",
    "Extractor  Automation": "提取器自动化",
    "Extractor Unlocked": "提取器已解锁",
    "Every City destroyed and rebuilt, every human inhabits the pillars, the gray walls give life, the\n                    humming machines give peace, and we humans will feed the structure, because the structure must grow.": "每一座被摧毁和重建的城市，每一个人都住在柱子上，灰色的墙给了生命，嗡嗡作响的机器给了和平，我们人类将为结构提供养分，因为结构必须成长。",
    "Earth crust starts being tempered.": "地壳开始变软。",
    "DISCLAIMER: the game is currently under development, future updates could radically\n                    change the game, this could lead to the inability to the system to accept previous saves": "免责声明:游戏目前正在开发中，未来的更新可能会彻底改变游戏，这可能导致系统无法接受以前的存档",
    "CURRENT ENDGAME, THANKS FOR PLAYING": "当前游戏结束，感谢您的参与",
    "Components are the heart of the structure, they decide the direction in which progress is made,\n                    never forget them, inventions will become obsolete, but not components.": "组件是结构的核心，它们决定着前进的方向，永远不要忘记它们，发明会过时，但组件不会。",
    "Energy flows in every crevice of the structure, never filling it enough, seeking a way to make this\n                    overflowing energy a stepping stone for your never ending expansion.": "能量在结构的每一个缝隙中流动，永远不会填满它，寻找一种方法，使这无限的能量成为你永无止境的扩张的垫脚石。",
    "ACTIVE COMPONENTS EFFECTS": "有效组件效果",
    "BUILD THE FIRST STRATUM": "建造第一层",
    "CLICK ON DATA TYPE \"LIGHT\" TO START, \"MEDIUM\" AND \"HEAVY\" WILL BE AVAIABLE\n                        WHEN THEIR BAR IS GREEN.\n                        WHEN A BAR IS FILLED IT WILL GENERATE AN UPGRADE OF THE FOLLOWING DATA TYPE.": "点击数据类型\"轻\"开始，\"中\"和\"重\"将可用，当他们的栏是绿色的。当一个数据条被填满时，它将生成以下数据类型的升级。",
    "Energy, life of the structure": "能量，结构的生命",
    "Catch\n                                        Asteroids": "捕捉\n小行星",
    "Catch Space\n                                        Dust": "捕捉太空\n尘埃",
    "do nothing": "什么都不做",
    "EVERY 10 UPGRADES IT BOOSTS THE COMPONENT": "每升级10次，它就会提升组件",
    "EXPLORATION": "探索",
    "COMPONENTS": "组件",
    "Communication": "通信",
    "Extractor Automation": "提取器自动化",
    "Glimpse in a black\n                                        hole": "对黑洞的一瞥",
    "Glimpse in the\n                                        sun": "在太阳下的一瞥",
    "Cells Producer": "细胞生产者",
    "BETTER CPU": "更好的CPU",
    "Rarity": "稀有度",
    "Components": "组件",
    "collects data faster, and unlocks new types of data": "更快地收集数据，并解锁新的数据类型",
    "Ally Synergy": "盟友协同",
    "Asteroid Cells Booster": "小行星细胞助推器",
    "Asteroid Enchancher": "小行星强化器",
    "Asteroid Data Booster": "小行星数据助推器",
    "Booster": "助推器",
    "Data Producer": "数据生产者",
    "Energy Synergy": "能量协同",
    "Multimaker": "多重制造者",
    "Tick Incrementer": "Tick增量器",
    "DATA AUTOMATION": "数据自动化",
    "COMPONENTS AUTOMATION": "组件自动化",
    "DEEP EXPLORATION": "深入探索",
    "EXPAND CPU": "扩展CPU",
    "Energy Layer": "能量层",
    "Extraction is slightly boosted": "提取量略有增加",
    "EXTRACTOR AUTOMATION": "提取器自动化",
    "FIRST EXPLORATION COMPONENTS": "第一个探索组件",
    "Hardware T1 layer is slightly cheaper": "硬件 T1 层稍微便宜一些",
    "FIRST STRATUM": "第一层",
    "Multimakers are slightly stronger": "多重制造者稍微强一些",
    "RARITY AUTOMATION": "稀有度自动化",
    "Rarity Layer": "稀有层",
    "you can extract more data from each type": "您可以从每种类型中提取更多数据",
    "Data Booster": "数据助推器",
    "Cells Booster": "细胞助推器",
    "Tick booster": "Tick助推器",
    "Boosters are stronger": "助推器更强",
    "Components Cost is reduced": "组件成本降低了",
    "Components rankup are slightly stronger": "组件升阶略微增强",
    "ACCUMULATOR": "蓄电池",
    "Catch Asteroids": "捕捉小行星",
    "Catch Some Asteroids! Because why not!": "抓住一些小行星!为什么不呢?",
    "Components Effect are slightly stronger": "组件效果略强",
    "Energy/s: 2^Level": "能量/秒: 2^等级",
    "glimpse in a black hole": "对黑洞的一瞥",
    "luce solare": "阳光",
    "Max Energy is boosted based on Energy/s": "最大能量根据能量/秒增加",
    "Max Energy: 10^Level": "能量上限: 10^等级",
    "SOLAR ENERGY": "太阳能",
    "TRANSFORMER": "变压器",
    "send a satellite inside a black hole, with some luck we will get something out of it": "把一颗卫星送入黑洞，运气好的话，我们会从中得到一些东西",
    "glimpse in a sun": "在太阳里一瞥",
    "send a satellite inside the sun, dont worry it wont burn up, its nighttime": "向太阳内部发射一颗卫星，别担心它不会燃烧，因为现在是夜间",
    "Space Dust Field": "太空尘埃场",
    "thousands of pounds of Space Dust fall on earth every day, lets collect some": "每天都有成千上万磅的太空尘埃落在地球上，让我们收集一些吧",
    "well this is kind of a waste": "这是一种浪费",
    "explore other things, maybe the fridge": "探索其他东西，比如冰箱",
    "Energized Structure": "通电结构",
    ", a boundless digital realm where imagination reshaped reality. The structure, omnipresent and ever-learning, granted or denied such requests, acting as humanity’s impartial overseer.": "这是一个无限的数字领域，想象重塑了现实。无所不在和不断学习的结构，作为人类公正的监督者，批准或拒绝这些要求。",
    "USER": "用户",
    "UPGRADE TOKEN": "升级代币",
    "TUTORIAL": "教程",
    "Black Sun": "黑日",
    "CORE": "核心",
    "HARDWARE": "硬件",
    "SOFTWARE COMPONENTS": "软件组件",
    "HARDWARE COMPONENTS": "硬件组件",
    "LEVEL UP:": "升级:",
    "New Home": "新家园",
    "OPTIONS": "选项",
    "PROGRESS": "进度",
    "RESET UPGRADES LEVELS": "重置升级等级",
    "UPGRADE TOKEN": "升级代币",
    "YES": "是",
    "Yet, the illusion of control slipped through his fingers. The lab felt alive, guided by an unseen force. Somewhere, beyond human comprehension, something had answered his ceaseless pursuit:": "然而，控制的幻觉从他的指间溜走了。在一股看不见的力量的指引下，实验室充满了活力。不知在什么地方，有什么东西在人类无法理解的范围内回应了他不断的追求：",
    "The economy soared; citizens flourished. Supercomputers, servers, and sleek metallic spires rose in days, forming a city of metal and ideas. No longer just a place—it became a nameless phenomenon.": "经济飙升；公民蓬勃发展。超级计算机、服务器和光滑的金属尖塔在几天内崛起，形成了一个金属和思想的城市。它不再只是一个地方，而是一种无名的现象。",
    "Rising City": "崛起之城",
    "Gaze at the Stars": "凝视星空",
    "DO YOU WANT TO RESET THE SAVE?": "是否要重置保存？",
    "FIRST CELL": "第一个细胞",
    "COMPONENTS SUMMARY": "组件汇总",
    "For solace, they built windows to the stars, stretching the horizon’s breadth. Some feared the structure’s growth would extinguish life, like a child stomping on an anthill. Others saw it as a mausoleum for ambition.": "为了安慰自己，他们建造了通往星星的窗户，把地平线延伸开去。一些人担心这座建筑的增长会毁灭生命，就像孩子踩在蚁丘上一样。其他人则将其视为野心的陵墓。",
    "EQUIP TOKEN TO SLOT": "装备代币到槽位",
    "COMPONENTS LIST": "组件列表",
    "Now, with Earth a glistening sea of metal, the need for resources grew insatiable. The structure stretched tendrils toward the stars, tasting the vastness of space and expanding into infinity.": "现在，随着地球成为闪闪发光的金属海洋，对资源的需求变得无法满足。这个结构把卷须伸向星星，品尝着浩瀚的太空，向无限延伸。",
    "Two centuries had passed since the first cell replicated. Humanity thrived—20 billion strong. On the machine’s birthday, joy reverberated as a monumental cake was presented, each layer symbolizing an epoch of progress. Though the machine could not eat, humanity gifted it a cookie, which it graciously accepted.": "Two centuries had passed since the first cell replicated. Humanity thrived—20 billion strong. On the machine’s birthday, joy reverberated as a monumental cake was presented, each layer symbolizing an epoch of progress. Though the machine could not eat, humanity gifted it a cookie, which it graciously accepted.",
    "The Beginning": "开端",
    "Resistance swelled. Regulations branded the project invasive. But the structure outpaced its detractors, transforming the city into an ecosystem of growth.": "抵抗情绪高涨。法规称该项目具有侵入性。但这种结构的发展速度超过了它的批评者，将这座城市转变为一个增长的生态系统。",
    "As they delved deeper, they discovered the machine’s secret: it needed space to replicate its cells. Yet, its adaptability allowed it to construct what it required, dismantling old structures to fashion its growing body.": "随着研究的深入，他们发现了机器的秘密：它需要空间来复制自己的细胞。然而，它的适应性使它能够建造它所需要的东西，拆除旧的结构来塑造它不断增长的身体。",
    "Across the city, the structure spread like wildfire, replacing crumbling facilities with towering edifices. Entire zones focused on fostering the machine’s evolution, each decision shaping the cityscape like brushstrokes on an endless canvas.": "在整个城市，建筑像野火一样蔓延，用高耸的大厦取代了摇摇欲坠的设施。整个区域都专注于促进机器的进化，每一个决定都像在无尽的画布上的一笔一划一样塑造了城市景观。",
    "But hope triumphed over fear. Birthrates soared, driven by lives unburdened by work, poverty, or illness. Faith in the structure grew, worshippers seeing it as a god of progress. Beneath a blackened sun, the world adapted, and whispers began—would the stars, too, one day succumb?": "但希望战胜了恐惧。由于没有工作、贫穷和疾病的负担，出生率飙升。人们对这座建筑的信心与日俱增，崇拜者将其视为进步之神。在黑暗的太阳下，世界适应了，低语开始了——星星有一天也会屈服吗？",
    "After years of frustration and failure, something inexplicable occurred. Machines, research meters, and data centers synchronized as if driven by an unseen hand.": "在经历了多年的挫折和失败之后，一些令人费解的事情发生了。机器、研究仪器和数据中心同步起来，仿佛有一只看不见的手在驱动。",
    "At midnight, a lone scientist toiled in isolation, captivated by his work on a groundbreaking invention: a piece of technology capable of infinite self-replication.": "午夜时分，一个孤独的科学家在孤独中辛勤工作，他被自己突破性的发明所吸引：一项能够无限自我复制的技术。",
    "But to the global scientific community, it was a glimpse into infinite potential. Despite its infancy, the technology drew eager young minds, desperate to unravel its mysteries.": "但对于全球科学界来说，这是对无限潜力的一瞥。尽管这项技术还处于起步阶段，但它吸引了渴望揭开其奥秘的年轻人。",
    "CHARGED": "充能",
    "CLICK A TOKEN": "点击一个令牌",
    "CLICK THE \"+\", CALLED SLOT": "点击\“+\”，称为插槽",
    "COMMUNICATION": "沟通",
    "COMMUNICATION COMPONENTS": "通信组件",
    "Consuming and expanding, the structure enveloped entire cities in its mechanical embrace—a clockwork marvel of neon streets, layers of transport, and swarms of adaptive drones.": "这种结构不断消耗和扩展，将整个城市包裹在它的机械拥抱中——霓虹灯街道、多层交通工具和成群的自适应无人机组成的时钟奇迹。",
    "Equip a Hardware Component into the slot to start activating various effects": "装备一个硬件组件到插槽开始激活各种效果",
    "Formulas that had confounded him for years resolved themselves, transforming his chaotic lab into a nexus of unexpected progress.": "多年来困扰他的公式自己解决了，把他混乱的实验室变成了意想不到的进步的纽带。",
    "home, surrounded by a landscape unrecognizable and inhospitable.": "家，周围的风景无法辨认，也不适宜居住。",
    "Hyperstructure Project": "外部表面工程",
    "In humanity’s myths, gods ruled the skies—Ra, Apollo, the Sun itself. Now, the Sun God was eclipsed by machines.": "在人类的神话中，诸神统治着天空——拉、阿波罗、太阳本身。现在，太阳神在机器面前黯然失色。",
    "Infinite growth without direction is chaos—a cancer devouring itself. Progress demands purpose.": "没有方向的无限增长是混乱的，就像癌症在吞噬自己。进步需要目标。",
    "Iron drones swept the earth, transforming it into a network of factories. A billion souls called the": "铁制无人机横扫地球，把它变成了一个工厂网络。十亿灵魂被称为",
    "KARDASHEV": "卡尔达舍夫",
    "Knowledge is Growth": "知识就是成长",
    "Life within the structure was tranquil. Every home housed android helpers; artificial intelligences nurtured and optimized existence.": "建筑内的生活是平静的。每个家庭都有机器人助手；人工智能培育和优化了生存。",
    "MAKE THE STRUCTURE GROW": "让结构成长",
    "Netsphere": "网域",
    "New Home": "新家",
    "News of the invention spread like wildfire across the country. Skeptics dismissed it as a passing gimmick or useless novelty.": "这项发明的消息像野火一样传遍了全国。持怀疑态度的人认为这是一种转瞬即逝的噱头或无用的新奇事物。",
    "NO": "否",
    "Nothing inefficient remained. Everything was rebuilt or repurposed with precision. Life’s necessities were provided, leaving creativity as humanity's sole currency.": "没有什么低效的东西留下。一切都被精确地重建或重新利用。生活的必需品被提供了，留下创造力作为人类唯一的货币。",
    "The lab disappeared in weeks, swallowed by the burgeoning organism. Soon, agencies worldwide invested heavily, and the": "实验室在几周内消失了，被迅速生长的有机体吞噬。很快，世界各地的机构都投入了大量资金",
    "Their plea was simple: a home where all could coexist—a sanctuary amidst the machine. Thus,": "他们的请求很简单：一个所有人都能共存的家——一个在机器中间的避难所。因此,",
    "Though alienation lingered, whispers of utopia grew louder. The structure offered stability but yearned for a new harmony. Humanity gazed skyward, imagining a life among the stars.": "尽管疏离感挥之不去，乌托邦的低语却越来越响亮。这种结构提供了稳定，但渴望一种新的和谐。人类凝视着天空，想象着在群星之间的生活。",
    "VERSION 0.1.54 (REVAMP UPDATE)": "版本0.1.54（修改更新）",
    "was born: a beacon of unity in an endless world of steel.": "诞生了：一个团结的灯塔在无尽的钢铁世界。",
    "was born.": "诞生了。",
    "When the last city fell to assimilation, a museum emerged, preserving virtual echoes of a world long past. Those seeking respite escaped to the": "当最后一座城市被同化时，一座博物馆出现了，它保留了很久以前世界的虚拟回声。那些寻求喘息的人逃到了",
    "PRODUCER": "生产者",
    "HARDWARE": "硬件",
    "SOFTWARE": "软件",
    "POTENTIAL": "潜力",
    "UNIT boosts UNIT EFFECT: ×": "单位提升单位效果: x",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "MULTIPLIES EXTRACTOR BASE X": "乘以提取器基数 x",
    "COMPLETE THE PROJECT: ": "完成项目: ",
    "cells/s": "细胞/秒",
    "adds to the base of cells/s: ": "添加到 细胞/秒 的基数:",
    "Automation: ": "自动化: ",
    "Component: ": "组件: ",
    "Idle time extension: ": "放置时间延长: ",
    "MILESTONE: ": "里程碑: ",
    "Options:": "选项:",
    "[SOFTWARE][producer]": "[软件][生产者]",
    "[SOFTWARE][booster]": "[软件][助推器]",
    "[HARDWARE][booster]": "[硬件][助推器]",
    "[HARDWARE][producer]": "[硬件][生产者]",
    "More cells -> More Cells/s X: ": "更多细胞 -> 更多细胞/秒 X: ",
    "More cells -> More Cells/s: ": "更多细胞 -> 更多细胞/秒: ",
    "[SOFTWARE]": "[软件]",
    "[HARDWARE]": "[硬件]",
    "[Booster]": "[助推器]",
    "data X: ": "数据 X: ",
    "each resource: x": "每种资源: x",
    "tickspeed X: ": "tick速度 X: ",
    "Energy Boosts Cell production: ": "能量提升细胞生产: ",
    "[COMMUNICATION][Synergy]": "[通信][协同]",
    "Level: ": "等级: ",
    "[COMMUNICATION][booster]": "[通信][助推器]",
    "all Asteroid explorations and components are boosted: ": "所有的小行星探索和组件被提升: ",
    "Asteroid Enchancer": "小行星增强器",
    "other components's effects are boosted based on this components level ": "其他组件的效果会基于该组件等级而提升 ",
    "[Synergy]": "[协同]",
    "Energy/s x:": "能量/秒 x:",
    "MAX POTENTIAL: ×": "最大潜力: x",
    "MAX POPULATION: ×": "最大人口: x",
    "POPULATION: ": "人口: ",
    "POPULATION/S: ": "人口/秒: ",
    "UNIT PRICE: ": "单位价格: ",
    "UNIT MAX LEVEL: ": "单位最大等级: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)\/([\d\.]+) ([\d\.]+)$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^reduces Energy\/s by (.+)$/, '降低 能量\/秒 $1'],
    [/^Removes Limit (.+) on Data, data (.+)$/, '移除数据限制 $1，数据 $2'],
    [/^HARDWARE LAYER AT (.+) CELLS$/, '硬件层在 $1 细胞'],
    [/^SOFTWARE LAYER AT (.+) CELLS$/, '软件层在 $1 细胞'],
    [/^EXPLORATION AT (.+) ENERGY$/, '探索在 $1 能量'],
    [/^PROJECTS AT (.+) DATA$/, '项目在 $1 数据'],
    [/^NEXT PROJECTS AT (.+) DATA$/, '下一个项目在 $1 数据'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) Cells$/, '$1e$2 细胞'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) CELLS$/, '$1 细胞'],
    [/^([\d\.]+) cells$/, '$1 细胞'],
    [/^([\d\.]+)e([\d\.,]+) Data$/, '$1e$2 数据'],
    [/^([\d\.]+)e([\d\.,]+) cells$/, '$1e$2 细胞'],
    [/^([\d\.]+)e([\d\.,]+) Asteroids$/, '$1e$2 小行星'],
    [/^([\d\.]+)e([\d\.,]+) asteroids$/, '$1e$2 小行星'],
    [/^asteroids: ([\d\.]+)$/, '小行星: $1'],
    [/^asteroids: ([\d\.]+)e([\d\.,]+)$/, '小行星: $1e$2'],
    [/^energy: ([\d\.]+)e([\d\.,]+)$/, '能量: $1e$2'],
    [/^Data \+ ([\d\.]+)\/s$/, '数据 \+ $1\/秒'],
    [/^cells: ([\d\.]+)$/, '细胞: $1'],
    [/^price: ([\d\.]+) data$/, '价格: $1 数据'],
    [/^price: ([\d\.]+)e([\d\.,]+) data$/, '价格: $1e$2 数据'],
    [/^EXPANSION: ([\d\.]+)$/, '扩张: $1'],
    [/^energy: ([\d\.]+)$/, '能量: $1'],
    [/^data: ([\d\.]+)$/, '数据: $1'],
    [/^data: ([\d\.]+)e([\d\.,]+)$/, '数据: $1e$2'],
    [/^cells: ([\d\.]+)e([\d\.,]+)$/, '细胞: $1e$2'],
    [/^effect: ([\d\.]+) \/ ([\d\.,]+)$/, '效果: $1 \/ $2'],
    [/^([\d\.]+) POPULATION$/, '$1 人口'],
    [/^([\d\.]+) ENERGY$/, '$1 能量'],
    [/^([\d\.]+) Cells$/, '$1 细胞'],
    [/^([\d\.]+) Asteroids$/, '$1 小行星'],
    [/^([\d\.]+) cells\/s$/, '$1 细胞\/秒'],
    [/^\+ ([\d\.]+) CELLS\/S$/, '\+ $1 细胞\/秒'],
    [/^\+ ([\d\.]+) POPULATION\/S$/, '\+ $1 人口\/秒'],
    [/^\+ ([\d\.]+) POTENTIAL\/S$/, '\+ $1 潜力\/秒'],
    [/^\+ ([\d\.]+) ENERGY\/S$/, '\+ $1 能量\/秒'],
    [/^([\d\.]+)e([\d\.,]+) Asteroids\/s$/, '$1e$2 小行星\/秒'],
    [/^([\d\.]+)e([\d\.,]+) cells\/s$/, '$1e$2 细胞\/秒'],
    [/^([\d\.]+)e([\d\.,]+) Data\/s$/, '$1e$2 数据\/秒'],
    [/^([\d\.]+)e([\d\.,]+) Energy\/s$/, '$1e$2 能量\/秒'],
    [/^([\d\.]+) Data$/, '$1 数据'],
    [/^([\d\.]+) Energy$/, '$1 能量'],
    [/^([\d\.]+) Energy\/s$/, '$1 能量\/秒'],
    [/^([\d\.]+)\/([\d\.]+) Energy\/s$/, '$1\/$2 能量\/秒'],
    [/^([\d\.]+)\/([\d\.]+) Energy$/, '$1\/$2 能量'],
    [/^(.+)\/(.+) Energy$/, '$1\/$2 能量'],
    [/^([\d\.]+)\/([\d\.]+)\| price: (.+) cells$/, '$1\/$2 能量\| 价格: $3 细胞'],
    [/^([\d\.]+) Data\/s$/, '$1 数据\/秒'],
    [/^([\d\.]+) Asteroids\/s$/, '$1 小行星\/秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) hour$/, '$1 小时'],
    [/^([\d\.,]+) POTENTIAL$/, '$1 潜力'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) TO THE EXTRACTOR BASE$/, '$1 到提取器基数'],
    [/^Adds \+([\d\.,]+) to the base$/, '增加 \+$1 到基数'],
    [/^SOFTWARE PACKAGE ([\d\.,]+)$/, '软件包 $1'],
    [/^HARDWARE PACKAGE ([\d\.,]+)$/, '硬件包 $1'],
    [/^Hardware ([\d\.,]+)$/, '硬件 $1'],
    [/^hardware ([\d\.,]+)$/, '硬件 $1'],
    [/^Software ([\d\.,]+)$/, '软件 $1'],
    [/^software ([\d\.,]+)$/, '软件 $1'],
    [/^TIER ([\d\.,]+)$/, '层级 $1'],
    [/^Communication ([\d\.,]+)$/, '沟通 $1'],
    [/^IDLE ([\d\.,]+)$/, '放置 $1'],
    [/^NEW RESOURCES PACKAGE ([\d\.,]+)$/, '新资源包 $1'],
    [/^Will Unlock K([\d\.,]+)$/, '将会解锁 K$1'],
    [/^LOADOUT ([\d\.,]+)$/, '预设 $1'],
    [/^multiplies Base x([\d\.,]+)$/, '乘以基数 x$1'],
    [/^COMMUNICATION PACKAGE ([\d\.,]+)$/, '通信包 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^effect: (.+)asteroids\/s$/, '效果：$1 小行星\/秒'],
    [/^Effect: (.+)$/, '效果：$1'],
    [/^Price: (.+) cells$/, '价格：$1 细胞'],
    [/^price: (.+) cells$/, '价格：$1 细胞'],
    [/^price: (.+) energy\/s$/, '价格：$1 能量\/秒'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);